import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

/**
 * 32 种技能初始数据
 */
const skills = [
  // ==================== 剑技能（4 种） ====================
  {
    id: 'sword_heavy_strike',
    name: '重击',
    description: '用力挥剑，造成 150% 伤害',
    type: 'Damage',
    weaponType: 'sword',
    damageMultiplier: 1.5,
    cooldown: 3,
    energyCost: 10,
    range: 50,
    icon: '⚔️',
  },
  {
    id: 'sword_whirlwind',
    name: '旋风斩',
    description: '旋转挥剑，对周围敌人造成 120% 伤害',
    type: 'Damage',
    weaponType: 'sword',
    damageMultiplier: 1.2,
    cooldown: 8,
    energyCost: 25,
    range: 50,
    radius: 100,
    icon: '🌪️',
  },
  {
    id: 'sword_block',
    name: '格挡',
    description: '举起盾牌，减少 50% 伤害，持续 5 秒',
    type: 'Shield',
    weaponType: 'sword',
    cooldown: 15,
    energyCost: 20,
    range: 0,
    duration: 5,
    icon: '🛡️',
  },
  {
    id: 'sword_charge',
    name: '冲锋',
    description: '向目标冲锋，造成 100% 伤害并眩晕 1 秒',
    type: 'Damage',
    weaponType: 'sword',
    damageMultiplier: 1.0,
    cooldown: 10,
    energyCost: 15,
    range: 150,
    icon: '💨',
  },

  // ==================== 斧技能（4 种） ====================
  {
    id: 'axe_chop',
    name: '劈砍',
    description: '猛烈劈砍，造成 180% 伤害',
    type: 'Damage',
    weaponType: 'axe',
    damageMultiplier: 1.8,
    cooldown: 4,
    energyCost: 15,
    range: 50,
    icon: '🪓',
  },
  {
    id: 'axe_berserk',
    name: '狂暴',
    description: '进入狂暴状态，攻击力 +30%，持续 8 秒',
    type: 'Buff',
    weaponType: 'axe',
    cooldown: 20,
    energyCost: 30,
    range: 0,
    duration: 8,
    icon: '😡',
  },
  {
    id: 'axe_blood_suck',
    name: '吸血打击',
    description: '造成伤害的 30% 转化为生命值',
    type: 'Damage',
    weaponType: 'axe',
    damageMultiplier: 1.3,
    cooldown: 12,
    energyCost: 20,
    range: 50,
    icon: '🩸',
  },
  {
    id: 'axe_shockwave',
    name: '震荡波',
    description: '震击地面，对周围敌人造成 100% 伤害并减速',
    type: 'Debuff',
    weaponType: 'axe',
    damageMultiplier: 1.0,
    cooldown: 15,
    energyCost: 25,
    range: 50,
    radius: 120,
    duration: 3,
    icon: '💥',
  },

  // ==================== 锤技能（4 种） ====================
  {
    id: 'hammer_smash',
    name: '猛击',
    description: '重锤猛击，造成 160% 伤害',
    type: 'Damage',
    weaponType: 'hammer',
    damageMultiplier: 1.6,
    cooldown: 4,
    energyCost: 15,
    range: 50,
    icon: '🔨',
  },
  {
    id: 'hammer_armor_break',
    name: '破甲攻击',
    description: '降低目标 30% 防御，持续 10 秒',
    type: 'Debuff',
    weaponType: 'hammer',
    cooldown: 15,
    energyCost: 20,
    range: 50,
    duration: 10,
    icon: '💔',
  },
  {
    id: 'hammer_stun',
    name: '眩晕重击',
    description: '重击头部，造成 120% 伤害并眩晕 2 秒',
    type: 'Damage',
    weaponType: 'hammer',
    damageMultiplier: 1.2,
    cooldown: 18,
    energyCost: 25,
    range: 50,
    icon: '⭐',
  },
  {
    id: 'hammer_counter',
    name: '反击',
    description: '格挡下次攻击并反击，造成 200% 伤害',
    type: 'Damage',
    weaponType: 'hammer',
    damageMultiplier: 2.0,
    cooldown: 20,
    energyCost: 30,
    range: 0,
    duration: 5,
    icon: '🔄',
  },

  // ==================== 匕首技能（4 种） ====================
  {
    id: 'dagger_backstab',
    name: '背刺',
    description: '从背后攻击，造成 200% 伤害',
    type: 'Damage',
    weaponType: 'dagger',
    damageMultiplier: 2.0,
    cooldown: 6,
    energyCost: 20,
    range: 40,
    icon: '🗡️',
  },
  {
    id: 'dagger_poison',
    name: '毒刃',
    description: '给武器涂毒，每次攻击附加 10 点伤害，持续 8 秒',
    type: 'Debuff',
    weaponType: 'dagger',
    cooldown: 15,
    energyCost: 25,
    range: 40,
    duration: 8,
    icon: '☠️',
  },
  {
    id: 'dagger_stealth',
    name: '隐身',
    description: '进入隐身状态，持续 5 秒',
    type: 'Buff',
    weaponType: 'dagger',
    cooldown: 30,
    energyCost: 40,
    range: 0,
    duration: 5,
    icon: '👻',
  },
  {
    id: 'dagger_evasion',
    name: '闪避',
    description: '闪避率 +50%，持续 6 秒',
    type: 'Buff',
    weaponType: 'dagger',
    cooldown: 20,
    energyCost: 25,
    range: 0,
    duration: 6,
    icon: '💨',
  },

  // ==================== 弓技能（4 种） ====================
  {
    id: 'bow_shot',
    name: '射击',
    description: '精准射击，造成 130% 伤害',
    type: 'Damage',
    weaponType: 'bow',
    damageMultiplier: 1.3,
    cooldown: 2,
    energyCost: 8,
    range: 300,
    icon: '🏹',
  },
  {
    id: 'bow_multishot',
    name: '多重箭',
    description: '同时射出 3 支箭，每支造成 80% 伤害',
    type: 'Damage',
    weaponType: 'bow',
    damageMultiplier: 0.8,
    cooldown: 10,
    energyCost: 30,
    range: 250,
    radius: 100,
    icon: '🎯',
  },
  {
    id: 'bow_eagle_eye',
    name: '鹰眼',
    description: '命中率 +50%，暴击率 +30%，持续 10 秒',
    type: 'Buff',
    weaponType: 'bow',
    cooldown: 20,
    energyCost: 25,
    range: 0,
    duration: 10,
    icon: '🦅',
  },
  {
    id: 'bow_escape',
    name: '逃脱射击',
    description: '向后跳跃并射击，造成 100% 伤害',
    type: 'Damage',
    weaponType: 'bow',
    damageMultiplier: 1.0,
    cooldown: 12,
    energyCost: 15,
    range: 300,
    icon: '🏃',
  },

  // ==================== 弩技能（3 种） ====================
  {
    id: 'crossbow_snipe',
    name: '狙击',
    description: '瞄准要害，造成 250% 伤害',
    type: 'Damage',
    weaponType: 'crossbow',
    damageMultiplier: 2.5,
    cooldown: 15,
    energyCost: 35,
    range: 400,
    icon: '🎯',
  },
  {
    id: 'crossbow_pierce',
    name: '穿透箭',
    description: '射出穿透箭，对一条直线上的敌人造成 150% 伤害',
    type: 'Damage',
    weaponType: 'crossbow',
    damageMultiplier: 1.5,
    cooldown: 12,
    energyCost: 25,
    range: 350,
    icon: '➹',
  },
  {
    id: 'crossbow_reload',
    name: '快速装填',
    description: '立即装填弩箭，攻击速度 +50%，持续 8 秒',
    type: 'Buff',
    weaponType: 'crossbow',
    cooldown: 20,
    energyCost: 20,
    range: 0,
    duration: 8,
    icon: '⚡',
  },

  // ==================== 法杖技能（4 种） ====================
  {
    id: 'staff_fireball',
    name: '火球术',
    description: '发射火球，造成 180% 魔法伤害',
    type: 'Damage',
    weaponType: 'staff',
    damageMultiplier: 1.8,
    cooldown: 3,
    energyCost: 20,
    range: 250,
    icon: '🔥',
  },
  {
    id: 'staff_frost',
    name: '冰霜新星',
    description: '释放冰霜，对周围敌人造成 120% 伤害并减速',
    type: 'Debuff',
    weaponType: 'staff',
    damageMultiplier: 1.2,
    cooldown: 10,
    energyCost: 30,
    range: 150,
    radius: 120,
    duration: 4,
    icon: '❄️',
  },
  {
    id: 'staff_lightning',
    name: '雷电术',
    description: '召唤雷电，对目标造成 200% 魔法伤害',
    type: 'Damage',
    weaponType: 'staff',
    damageMultiplier: 2.0,
    cooldown: 8,
    energyCost: 35,
    range: 250,
    icon: '⚡',
  },
  {
    id: 'staff_teleport',
    name: '传送',
    description: '瞬间移动到目标位置',
    type: 'Dash',
    weaponType: 'staff',
    cooldown: 20,
    energyCost: 40,
    range: 200,
    icon: '✨',
  },

  // ==================== 魔典技能（3 种） ====================
  {
    id: 'tome_heal',
    name: '治疗术',
    description: '恢复目标 100 点生命值',
    type: 'Heal',
    weaponType: 'tome',
    healAmount: 100,
    cooldown: 5,
    energyCost: 25,
    range: 200,
    icon: '💚',
  },
  {
    id: 'tome_shield',
    name: '神圣护盾',
    description: '为目标添加护盾，吸收 80 点伤害，持续 8 秒',
    type: 'Shield',
    weaponType: 'tome',
    cooldown: 15,
    energyCost: 30,
    range: 200,
    duration: 8,
    icon: '🛡️',
  },
  {
    id: 'tome_cleanse',
    name: '净化',
    description: '移除目标所有负面状态',
    type: 'Buff',
    weaponType: 'tome',
    cooldown: 20,
    energyCost: 35,
    range: 200,
    icon: '✨',
  },
]

async function main() {
  console.log('开始插入技能数据...')

  for (const skill of skills) {
    await prisma.skill.upsert({
      where: { id: skill.id },
      update: skill,
      create: skill,
    })
    console.log(`  - ${skill.name} (${skill.id})`)
  }

  console.log(`✅ 成功插入 ${skills.length} 个技能`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
